# Generated by Django 4.2.7 on 2024-02-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_alter_faq_faq_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='faq_slug',
        ),
        migrations.AlterField(
            model_name='faq',
            name='ques',
            field=models.CharField(max_length=150),
        ),
    ]
