# Generated by Django 4.2.7 on 2024-04-28 10:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_remove_faq_faq_slug_alter_faq_ques'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=150, verbose_name='Question')),
                ('ans', tinymce.models.HTMLField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'FAQs',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.DeleteModel(
            name='faq',
        ),
    ]
