# Generated by Django 3.2.1 on 2024-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0005_rename_add_faq_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='ques',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
