# Generated by Django 4.2.7 on 2024-02-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(max_length=150)),
                ('donoremail', models.CharField(max_length=150)),
                ('donorphone', models.CharField(max_length=150)),
                ('donoraddress', models.CharField(max_length=150)),
                ('donorblood', models.CharField(max_length=150)),
                ('donorage', models.CharField(max_length=150)),
                ('donorgender', models.CharField(max_length=150)),
            ],
        ),
    ]
