# Generated by Django 4.2.7 on 2024-02-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donorimage',
            field=models.ImageField(blank=True, null=True, upload_to='#'),
        ),
    ]
