# Generated by Django 4.2.7 on 2024-02-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donor_donorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donorimage',
            field=models.ImageField(blank=True, null=True, upload_to='Donor image'),
        ),
    ]
