# Generated by Django 4.2.7 on 2024-03-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_alter_donor_donorimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='donor',
        ),
    ]
