# Generated by Django 4.2.7 on 2024-02-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donation_camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campname', models.CharField(max_length=150)),
                ('campdate', models.CharField(max_length=150)),
                ('camptime', models.CharField(max_length=150)),
                ('campaddress', models.CharField(max_length=150)),
                ('campcontact', models.CharField(max_length=150)),
                ('camporganizer', models.CharField(max_length=150)),
            ],
        ),
    ]
