# Generated by Django 4.2.7 on 2024-02-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donationcamp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donation_camp',
            new_name='donationCamp',
        ),
    ]
