# Generated by Django 4.2.7 on 2024-03-23 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0012_remove_userprofile_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodbankname', models.CharField(max_length=150)),
                ('bloodbankemail', models.CharField(max_length=150)),
                ('bloodbankphone', models.CharField(max_length=150)),
                ('bloodbanklink', models.CharField(max_length=150)),
                ('bloodbanklocation', models.CharField(max_length=150)),
                ('bloodbankgroups', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
