# Generated by Django 4.2.7 on 2024-04-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_bloodbank_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='donor_donationcount',
            field=models.IntegerField(default=0),
        ),
    ]
