# Generated by Django 4.2.7 on 2024-04-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_userprofile_donor_donationcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='bloodbankaccreditations',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='bloodbanktypes',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
