# Generated by Django 4.2.7 on 2024-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_bloodbank_bloodbankaccreditations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodbank',
            options={'verbose_name': 'Blood Bank', 'verbose_name_plural': 'Blood Bank'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Donor', 'verbose_name_plural': 'Donor'},
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodbankaccreditations',
            field=models.CharField(max_length=150, verbose_name='Accreditaions'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodbankemail',
            field=models.CharField(max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodbankgroups',
            field=models.CharField(max_length=150, verbose_name='Available Groups'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodbanklink',
            field=models.CharField(max_length=150, verbose_name='Website Link'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodbanklocation',
            field=models.CharField(max_length=150, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodbankname',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodbankphone',
            field=models.CharField(max_length=150, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='bloodbanktypes',
            field=models.CharField(max_length=150, verbose_name='Types'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Bloodbank-picture', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bloodgroup',
            field=models.CharField(max_length=100, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='donor_donationcount',
            field=models.IntegerField(default=0, verbose_name='Dontion Count'),
        ),
    ]
