# Generated by Django 3.2.1 on 2024-07-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20240516_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_donation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
