# Generated by Django 4.2.7 on 2024-03-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipient', '0002_alter_recipient_recipientdonationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='recipienttime',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
