# Generated by Django 4.2.7 on 2024-04-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipient', '0003_recipient_recipienttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='recipientemail',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
