# Generated by Django 3.2.1 on 2024-05-07 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recipient', '0006_alter_donationcamp_options_alter_recipient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
