# Generated by Django 3.2.1 on 2024-05-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipient', '0008_alter_recipient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='user',
        ),
    ]
