# Generated by Django 3.2.1 on 2024-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipient', '0013_alter_recipient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcamp',
            name='campaddress',
            field=models.TextField(verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='donationcamp',
            name='camporganizer',
            field=models.TextField(verbose_name='Organizer'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='recipientcondition',
            field=models.TextField(verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='recipientlocation',
            field=models.TextField(verbose_name='Location'),
        ),
    ]
