# Generated by Django 3.2.1 on 2024-07-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipient', '0014_auto_20240516_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='recipientdate',
            field=models.DateField(max_length=150, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='recipienttime',
            field=models.TimeField(default=None, max_length=150, verbose_name='Time'),
        ),
    ]
