# Generated by Django 3.2.1 on 2024-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipient', '0015_auto_20240708_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcamp',
            name='campdate',
            field=models.DateField(max_length=150, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='donationcamp',
            name='camptime',
            field=models.TimeField(max_length=150, verbose_name='Time'),
        ),
    ]
