# Generated by Django 4.2.7 on 2024-03-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloodbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodbankname', models.CharField(max_length=150)),
                ('bloodbankemail', models.CharField(max_length=150)),
                ('bloodbankphone', models.CharField(max_length=150)),
                ('bloodbanklink', models.CharField(max_length=150)),
                ('bloodbanklocation', models.CharField(max_length=150)),
                ('bloodbankgroups', models.CharField(max_length=150)),
            ],
        ),
    ]
