# Generated by Django 4.2.7 on 2024-03-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bloodbank',
        ),
    ]
